# Configuration for probot-auto-merge - https://github.com/bobvanderlinden/probot-auto-merge

minApprovals:
  MEMBER: 0
  COLLABORATOR: 0
maxRequestedChanges:
  COLLABORATOR: 0

updateBranch: true
deleteBranchAfterMerge: true
mergeMethod: squash
reportStatus: true

blockingLabels:
- blocked
requiredLabels:
- auto-merge
blockingTitleRegex: '\bwip\b'
